---
title: "Messaging"
---

## Sending and receiving messages

Agents interact with each other using messages. A [Message](https://org-arl.github.io/fjage/javadoc/index.html?org/arl/fjage/Message.html) is usually tagged with a [Performative](https://org-arl.github.io/fjage/javadoc/index.html?org/arl/fjage/Performative.html) that defines the purpose of the message, and is uniquely identified by a message identifier. A message is also usually associated with a sender and a recipient `AgentID`. If a message is sent in reply to another message, the original message's message identifier is included as a `inReplyTo` property of the reply message. This allows the sender to associate the reply with the original request/query message.

Although the [Message](https://org-arl.github.io/fjage/javadoc/index.html?org/arl/fjage/Message.html) class provides all the basic attributes of a message, it does not provide any fields to hold the message content. Typical messages will extend the [Message](https://org-arl.github.io/fjage/javadoc/index.html?org/arl/fjage/Message.html) class and add relevant content fields.

Request message:

``` groovy
class WeatherForecastReq extends org.arl.fjage.Message {
  WeatherForecastReq() {
    super(Performative.REQUEST)
  }
  String city, country
}
```

Response message:

``` groovy
class WeatherForecast extends org.arl.fjage.Message {
  WeatherForecast() {
    super(Performative.INFORM)
  }
  WeatherForecast(Message req) {
    super(req, Performative.INFORM)   // create a response with inReplyTo = req
    city = req.city
    country = req.country
  }
  String city, country
  float minTemp, maxTemp, probRain
}
```

A client agent may send a weather forecast request to another agent named "WeatherStation":

``` groovy
send new WeatherForecastReq(city: 'London', country: 'UK', recipient: agent('WeatherStation'))
```

The "WeatherStation" agent would receive the request and send back a reply. Although messages may be received using an agent's `receive()` method, the preferred way to process messages is using a [message behavior](behaviors.qmd#message-behavior):

``` groovy
class MyWeatherStation extends org.arl.fjage.Agent {
  void init() {
    add new MessageBehavior(WeatherForecastReq, { req ->
      log.info "Weather forecast request for ${req.city}, ${req.country}"
      def rsp = new WeatherForecast(req)
      rsp.minTemp = 10
      rsp.maxTemp = 25
      rsp.probRain = 0.25
      send rsp
    })
  }
}
```

The client agent would then receive the message, either through a message behavior or by explicitly calling `receive()`. An easier alternative is to send a request and wait for the associated response via the `request()` method:

``` groovy
def req = new WeatherForecastReq(city: 'London', country: 'UK', recipient: agent('WeatherStation'))
def rsp = request req, 1000         // 1000 ms timeout for reply
println "The lowest temperature today is ${rsp?rsp.minTemp:'unknown'}"
```

## Generic messages

Although it usually makes sense to create message classes for specific interactions, there are times when it can be useful to send a generic message with key-value pairs. This functionality is provided by the [GenericMessage](https://org-arl.github.io/fjage/javadoc/index.html?org/arl/fjage/GenericMessage.html) class, which provides a `java.util.Map` interface. In Groovy, this provides a nice syntax that allows the keys to work like dynamic attributes of the message. A weather forecast service implemented using generic messages is shown below.

Server code:

``` groovy
import org.arl.fjage.*

class MyWeatherStation extends Agent {
  void init() {
    add new MessageBehavior({ msg ->
      if (msg.performative == Performative.REQUEST && msg.type == 'WeatherForecast') {
        log.info "Weather forecast request for ${msg.city}, ${msg.country}"
        def rsp = new GenericMessage(msg, Performative.INFORM)
        rsp.minTemp = 10
        rsp.maxTemp = 25
        rsp.probRain = 0.25
        send rsp
      }
    })
  }
}
```

Client code snippet:

``` groovy
def req = new GenericMessage(agent('WeatherStation'), Performative.REQUEST)
req.type = 'WeatherForecast'
req.city = 'London'
req.country = 'UK'
def rsp = request req, 1000         // 1000 ms timeout for reply
println "The lowest temperature today is ${rsp?rsp.minTemp:'unknown'}"
```

## Alternate syntax

Let us assume we have an `AgentID` for the "WeatherStation":

``` groovy
def weatherStation = agent('WeatherStation')
```

It is sometimes nicer to be able to use a syntax like this:

``` groovy
weatherStation.send new WeatherForecastReq(city: 'London', country: 'UK')
```

or:

``` groovy
def rsp = weatherStation.request new WeatherForecastReq(city: 'London', country: 'UK')
```

or perhaps even:

``` groovy
def rsp = weatherStation << new WeatherForecastReq(city: 'London', country: 'UK')
```

This alternate syntax sometimes yields more readable code, and is supported by fjåge. It is important, however, to remember that the message is sent in the context of the client agent that provided us with the `AgentID`. Any `AgentID` returned by an agent (by methods such as `agent()`, `agentForService()`, etc) is associated with or *owned by* that agent. When this `AgentID` is used with the above syntax, the message is actually sent using the associated agent.

::: {.callout-note}
If you create an `AgentID` explicitly as `new AgentID('WeatherStation')`, it does not have an owner, and therefore cannot be used with this alternate syntax. It can, however, be used with the original syntax as a recipient for a message.
:::

## Handling responses without blocking

The `request()` method blocks the calling behavior until a response arrives or the timeout expires. If you would rather carry on and be told when the response arrives, prepare the request with `prepareRequest()`, add a handler for each kind of response you care about, and send it:

``` groovy
def req = new WeatherForecastReq(city: 'London', country: 'UK', recipient: agent('WeatherStation'))
prepareRequest(req)
  .onInform({ rsp -> println "The lowest temperature today is ${rsp.minTemp}" })
  .onRefuse({ rsp -> println 'The weather station refused the request' })
  .onTimeout(1000, { println 'The weather station did not respond' })
  .send()
```

The [RequestSender](https://org-arl.github.io/fjage/javadoc/index.html?org/arl/fjage/RequestSender.html) returned by `prepareRequest()` provides the handlers `onAgree()`, `onRefuse()`, `onFailure()` and `onInform()` for responses with those performatives, `otherwise()` for responses with any other performative, and `onTimeout()`. The request ends with the first response that has a handler, or when a timeout expires. A response without a handler is ignored, and the agent continues to wait.

The handlers are called from the agent's thread, just like behaviors, so they can safely access the agent's state.

`send()` returns immediately with a `Future` that can be used to cancel the request. If you want to wait for the request to end, use `sendAndWait()` in place of `send()`. It returns the response that ended the request, or `null` on timeout.

### Requests with several responses

Some requests are answered with more than one message. For example, an agent may respond with an `AGREE` to accept a long task, and follow up with one or more `INFORM` messages as the task progresses. Such requests are prepared with `prepareMultiResponseRequest()`. Each handler returns `true` to end the request, or `false` to continue to wait for more responses:

``` groovy
prepareMultiResponseRequest(req)
  .onAgree({ rsp ->
    println 'Request accepted'
    false                           // more responses to come
  })
  .onInform({ rsp ->
    println "Progress: ${rsp.progress}%"
    rsp.progress >= 100             // end the request once the task is complete
  })
  .onTimeout(10000, { println 'Gave up waiting' })
  .send()
```

The [MultiResponseRequestSender](https://org-arl.github.io/fjage/javadoc/index.html?org/arl/fjage/MultiResponseRequestSender.html) differs from the `RequestSender` in a few ways:

* The request ends only when a handler returns `true`, or when a timeout expires.
* If there is no handler for it, a `REFUSE` or `FAILURE` response ends the request. Any other response without a handler is ignored.
* Every response to the request restarts the timeouts, so a timeout is the longest time to wait between responses, and not the time allowed for the whole request.
* `sendAndWait()` returns the response that ended the request, or `null` on timeout.

::: {.callout-note}
A Groovy closure returns the value of its last expression. A handler that ends with a statement that has no value, such as a `println`, is treated as returning `false`, and the request continues to wait.
:::

## Publishing and subscribing

So far we have sent messages to recipients whose `AgentID` we know. There are times when we may want to publish a message without explicitly knowing who the recipients are. All agents *subscribing* to the *topic* that we publish on would then receive the published message.

This is supported by fjåge using the messaging constructs we have already encountered. Messages can be sent to topics in the same way that messages are sent to other agents. A topic is simply a special `AgentID`:

``` groovy
def weatherChannel = topic('WeatherChannel')
```

Instead of using a `String` for the topic name, it is also possible (and usually recommended) to use Enums:

``` groovy
enum Topics {
  WEATHER_CHANNEL,
  TSUNAMI_WARNING_CHANNEL
}
```

and:

``` groovy
def weatherChannel = topic(Topics.WEATHER_CHANNEL)
```

Agents can subscribe to the topic of interest, typically in their `init()` method:

``` groovy
subscribe weatherChannel
```

Messages can be sent to all agents subscribing to the topic:

``` groovy
def forecast = new WeatherForecast(city: 'London', country: 'UK', minTemp: 10, maxTemp: 25, probRain: 0.25)
weatherChannel.send forecast
```

Agents that no longer wish to receive messages on a topic may also unsubscribe from the topic:

``` groovy
unsubscribe weatherChannel
```

## Cloning messages

By default, a message delivered to another agent in the same container is the original object, and not a copy. This has some subtle but important implications. If an agent modifies a message after sending it, this can lead to unexpected behaviors.

Let's take an example:

``` groovy
def msg = new GenericMessage()
msg.text = 'Hello!'
agent('Susan').send msg
msg.text = 'Holla!'
agent('Lola').send msg
```

If the message is delivered to Susan before the agent modifies the message, Susan gets a "Hello!" message and then Lola gets a "Holla!" message. If the message is modified after delivery to Susan, but before she has had a chance to read it, both Susan and Lola get a "Holla!" message. If the message is modified and sent to Lola before it is delivered to Susan, the recipient of the message changes, and two copies of "Holla!" get delivered to Lola and nothing gets delivered to Susan. As you can see, the behavior is indeterminate and a debugging nightmare!

Fortunately, there are several simple ways around this:

1.  Do not modify a message once it is sent. The code would then look like this:

    ``` groovy
    def msg = new GenericMessage()
    msg.text = 'Hello!'
    agent('Susan').send msg
    msg = new GenericMessage()        // create a new message, don't modify the old one
    msg.text = 'Holla!'
    agent('Lola').send msg
    ```

2.  Send a copy of the message, rather than the original. You can then freely modify the original:

    ``` groovy
    def msg = new GenericMessage()
    msg.text = 'Hello!'
    agent('Susan').send clone(msg)    // send a copy of the message
    msg.text = 'Holla!'
    agent('Lola').send msg
    ```

3.  Ask the container to always send copies of messages rather than the original, and then you can use the original code without a problem:

    ``` groovy
    container.autoClone = true
    ```

The cloning of the message is accomplished using the `org.apache.commons.lang3.SerializationUtils` class. This performs a deep clone (clones all objects contained in the message) by serializing the entire message, and then deserializing it. This is very portable (as long as your message is `Serializable`), but somewhat slow. A faster deep cloning implementation is available from `com.rits.cloning.Cloner`, but it is less portable (it seems to have trouble dealing with some Groovy messages). This library is already included as a dependency of fjåge, so if you wish to try this implementation for your application, simply switch to using the fast cloner:

``` groovy
container.cloner = Container.FAST_CLONER
```
